<?php

namespace ContainerK67EvxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JDPgSemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JDPgSem' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JDPgSem'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarDate' => ['privates', 'App\\Data\\Calendar', 'getCalendarService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reservations' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'calendarDate' => 'App\\Data\\Calendar',
            'doctrine' => '?',
            'paginator' => '?',
            'reservations' => 'App\\Repository\\ReservationRepository',
            'security' => '?',
        ]);
    }
}
