<?php

namespace ContainerOv1Cpm1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDwellingMetaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DwellingMetaType' shared autowired service.
     *
     * @return \App\Form\DwellingMetaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DwellingMetaType.php';

        return $container->privates['App\\Form\\DwellingMetaType'] = new \App\Form\DwellingMetaType();
    }
}
