<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8rRqYh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8rRqYh/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerY8rRqYh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerY8rRqYh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerY8rRqYh\App_KernelProdContainer([
    'container.build_hash' => 'Y8rRqYh',
    'container.build_id' => '0eeb6107',
    'container.build_time' => 1659215185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8rRqYh');
