<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Department extends \App\Entity\Department implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nomUppercase', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nomSoundex', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'cities'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nomUppercase', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'nomSoundex', '' . "\0" . 'App\\Entity\\Department' . "\0" . 'cities'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Department $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?\App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(?\App\Entity\Country $country): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomUppercase(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomUppercase', []);

        return parent::getNomUppercase();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomUppercase(string $nomUppercase): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomUppercase', [$nomUppercase]);

        return parent::setNomUppercase($nomUppercase);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSoundex(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSoundex', []);

        return parent::getNomSoundex();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSoundex(string $nomSoundex): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSoundex', [$nomSoundex]);

        return parent::setNomSoundex($nomSoundex);
    }

    /**
     * {@inheritDoc}
     */
    public function getCities(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCities', []);

        return parent::getCities();
    }

    /**
     * {@inheritDoc}
     */
    public function addCity(\App\Entity\City $city): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCity', [$city]);

        return parent::addCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCity(\App\Entity\City $city): \App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCity', [$city]);

        return parent::removeCity($city);
    }

}
