<?php

namespace ContainerQxls9f0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JefGmHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JefGm_H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JefGm_H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.CWpq9pn', 'get_ServiceLocator_CWpq9pnService', true],
            'App\\Controller\\CheckoutController::habitation' => ['privates', '.service_locator.lp4ext1', 'get_ServiceLocator_Lp4ext1Service', true],
            'App\\Controller\\HostController::host' => ['privates', '.service_locator.SnndV9S', 'get_ServiceLocator_SnndV9SService', true],
            'App\\Controller\\LocationController::location' => ['privates', '.service_locator.vrNJZlt', 'get_ServiceLocator_VrNJZltService', true],
            'App\\Controller\\ProductController::check' => ['privates', '.service_locator.VS5asUu', 'get_ServiceLocator_VS5asUuService', true],
            'App\\Controller\\ProductController::habitation' => ['privates', '.service_locator.lp4ext1', 'get_ServiceLocator_Lp4ext1Service', true],
            'App\\Controller\\ProductController::paiement' => ['privates', '.service_locator.pDLeaJ2', 'get_ServiceLocator_PDLeaJ2Service', true],
            'App\\Controller\\SearchController::index' => ['privates', '.service_locator.sTu1uJn', 'get_ServiceLocator_STu1uJnService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.J3Xxbfm', 'get_ServiceLocator_J3XxbfmService', true],
            'App\\Controller\\UsersController::dashboard' => ['privates', '.service_locator.a4BSXtv', 'get_ServiceLocator_A4BSXtvService', true],
            'App\\Controller\\UsersController::historical' => ['privates', '.service_locator.KEMuaGy', 'get_ServiceLocator_KEMuaGyService', true],
            'App\\Controller\\UsersController::message' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\UsersController::payment' => ['privates', '.service_locator.8kODZ1N', 'get_ServiceLocator_8kODZ1NService', true],
            'App\\Controller\\UsersController::register' => ['privates', '.service_locator.NIwGBiD', 'get_ServiceLocator_NIwGBiDService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.CWpq9pn', 'get_ServiceLocator_CWpq9pnService', true],
            'App\\Controller\\CheckoutController:habitation' => ['privates', '.service_locator.lp4ext1', 'get_ServiceLocator_Lp4ext1Service', true],
            'App\\Controller\\HostController:host' => ['privates', '.service_locator.SnndV9S', 'get_ServiceLocator_SnndV9SService', true],
            'App\\Controller\\LocationController:location' => ['privates', '.service_locator.vrNJZlt', 'get_ServiceLocator_VrNJZltService', true],
            'App\\Controller\\ProductController:check' => ['privates', '.service_locator.VS5asUu', 'get_ServiceLocator_VS5asUuService', true],
            'App\\Controller\\ProductController:habitation' => ['privates', '.service_locator.lp4ext1', 'get_ServiceLocator_Lp4ext1Service', true],
            'App\\Controller\\ProductController:paiement' => ['privates', '.service_locator.pDLeaJ2', 'get_ServiceLocator_PDLeaJ2Service', true],
            'App\\Controller\\SearchController:index' => ['privates', '.service_locator.sTu1uJn', 'get_ServiceLocator_STu1uJnService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.J3Xxbfm', 'get_ServiceLocator_J3XxbfmService', true],
            'App\\Controller\\UsersController:dashboard' => ['privates', '.service_locator.a4BSXtv', 'get_ServiceLocator_A4BSXtvService', true],
            'App\\Controller\\UsersController:historical' => ['privates', '.service_locator.KEMuaGy', 'get_ServiceLocator_KEMuaGyService', true],
            'App\\Controller\\UsersController:message' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\UsersController:payment' => ['privates', '.service_locator.8kODZ1N', 'get_ServiceLocator_8kODZ1NService', true],
            'App\\Controller\\UsersController:register' => ['privates', '.service_locator.NIwGBiD', 'get_ServiceLocator_NIwGBiDService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CheckoutController::habitation' => '?',
            'App\\Controller\\HostController::host' => '?',
            'App\\Controller\\LocationController::location' => '?',
            'App\\Controller\\ProductController::check' => '?',
            'App\\Controller\\ProductController::habitation' => '?',
            'App\\Controller\\ProductController::paiement' => '?',
            'App\\Controller\\SearchController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UsersController::dashboard' => '?',
            'App\\Controller\\UsersController::historical' => '?',
            'App\\Controller\\UsersController::message' => '?',
            'App\\Controller\\UsersController::payment' => '?',
            'App\\Controller\\UsersController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CheckoutController:habitation' => '?',
            'App\\Controller\\HostController:host' => '?',
            'App\\Controller\\LocationController:location' => '?',
            'App\\Controller\\ProductController:check' => '?',
            'App\\Controller\\ProductController:habitation' => '?',
            'App\\Controller\\ProductController:paiement' => '?',
            'App\\Controller\\SearchController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UsersController:dashboard' => '?',
            'App\\Controller\\UsersController:historical' => '?',
            'App\\Controller\\UsersController:message' => '?',
            'App\\Controller\\UsersController:payment' => '?',
            'App\\Controller\\UsersController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
