<?php

namespace ContainerAudYYUs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STu1uJnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sTu1uJn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sTu1uJn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', 'App\\Data\\Calendar', 'getCalendarService', true],
            'dwelRep' => ['privates', 'App\\Repository\\DwellingRepository', 'getDwellingRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'calendar' => 'App\\Data\\Calendar',
            'dwelRep' => 'App\\Repository\\DwellingRepository',
            'paginator' => '?',
        ]);
    }
}
