<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z9VlXKMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Z9VlXKM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z9VlXKM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarDate' => ['privates', 'App\\Data\\Calendar', 'getCalendarService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'dwelRep' => ['privates', 'App\\Repository\\DwellingRepository', 'getDwellingRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'reservRep' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'calendarDate' => 'App\\Data\\Calendar',
            'doctrine' => '?',
            'dwelRep' => 'App\\Repository\\DwellingRepository',
            'mailer' => '?',
            'reservRep' => 'App\\Repository\\ReservationRepository',
            'security' => '?',
        ]);
    }
}
