<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDwellingControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DwellingController' shared autowired service.
     *
     * @return \App\Controller\DwellingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DwellingController'] = $instance = new \App\Controller\DwellingController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\DwellingController', $container));

        return $instance;
    }
}
