<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDwellingTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DwellingType' shared autowired service.
     *
     * @return \App\Form\DwellingType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DwellingType'] = new \App\Form\DwellingType(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
