<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDwellingMetaTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DwellingMetaType' shared autowired service.
     *
     * @return \App\Form\DwellingMetaType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DwellingMetaType'] = new \App\Form\DwellingMetaType();
    }
}
