<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFunctionsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FunctionsRepository' shared autowired service.
     *
     * @return \App\Repository\FunctionsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FunctionsRepository'] = new \App\Repository\FunctionsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
