<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PostsRepository' shared autowired service.
     *
     * @return \App\Repository\PostsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PostsRepository'] = new \App\Repository\PostsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Repository\\PostMetaRepository'] ?? $container->load('getPostMetaRepositoryService')));
    }
}
