<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationMetaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ReservationMetaRepository' shared autowired service.
     *
     * @return \App\Repository\ReservationMetaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReservationMetaRepository'] = new \App\Repository\ReservationMetaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
