<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserMetaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UserMetaRepository' shared autowired service.
     *
     * @return \App\Repository\UserMetaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UserMetaRepository'] = new \App\Repository\UserMetaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
