<?php

namespace ContainerY8rRqYh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserMetaTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UserMetaType' shared autowired service.
     *
     * @return \App\Form\UserMetaType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserMetaType'] = new \App\Form\UserMetaType();
    }
}
