<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhK6HNb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhK6HNb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJhK6HNb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJhK6HNb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJhK6HNb\App_KernelDevDebugContainer([
    'container.build_hash' => 'JhK6HNb',
    'container.build_id' => 'fbf71407',
    'container.build_time' => 1656952160,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhK6HNb');
