<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNJ9nukx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNJ9nukx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNJ9nukx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNJ9nukx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNJ9nukx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NJ9nukx',
    'container.build_id' => 'aa30ec8f',
    'container.build_time' => 1658143595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNJ9nukx');
