<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \App\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'alpha2', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'alpha3', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nameEnGb', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nameFr', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'europe', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'dwellings', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'users'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'alpha2', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'alpha3', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nameEnGb', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nameFr', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'europe', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'dwellings', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'users'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(int $code): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha2', []);

        return parent::getAlpha2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlpha2(string $alpha2): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlpha2', [$alpha2]);

        return parent::setAlpha2($alpha2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha3', []);

        return parent::getAlpha3();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlpha3(string $alpha3): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlpha3', [$alpha3]);

        return parent::setAlpha3($alpha3);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameEnGb(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameEnGb', []);

        return parent::getNameEnGb();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEnGb(string $nameEnGb): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEnGb', [$nameEnGb]);

        return parent::setNomEnGb($nameEnGb);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameFr', []);

        return parent::getNameFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameFr(string $nameFr): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameFr', [$nameFr]);

        return parent::setNameFr($nameFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getEurope(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEurope', []);

        return parent::getEurope();
    }

    /**
     * {@inheritDoc}
     */
    public function setEurope(bool $europe): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEurope', [$europe]);

        return parent::setEurope($europe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDwellings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDwellings', []);

        return parent::getDwellings();
    }

    /**
     * {@inheritDoc}
     */
    public function addDwelling(\App\Entity\Dwelling $dwelling): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDwelling', [$dwelling]);

        return parent::addDwelling($dwelling);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDwelling(\App\Entity\Dwelling $dwelling): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDwelling', [$dwelling]);

        return parent::removeDwelling($dwelling);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\Users $user): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\Users $user): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

}
